services:
  postgresql:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus
      POSTGRES_DB: nexus_solutions
    ports:
      - "5433:5432"
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      SERVICES: s3
    #      AWS_REGION: us-east-1
    #      AWS_ACCESS_KEY: test
    #      AWS_SECRET_ACCESS_KEY: test
    ports:
      - "4566:4566"